Added support for writing AVR eeprom.

diff --git a/avrdude-scp b/avrdude-scp
--- a/avrdude-scp
+++ b/avrdude-scp
@@ -8,6 +8,10 @@ SESSION=$(date +%Y%m%d%H%M%S)_$(cat /dev/urandom | tr -cd [:alnum:] | head -c 8)
 CONTROL_PATH='ControlPath=~/.ssh/%r@%h:%p.conn.'$SESSION
 WORKING_DIR=$(pwd)
 EXECUTION_ATTEMPTS=1
+FLASH_PATH=""
+FLASH_FILENAME=""
+EEPROM_PATH=""
+EEPROM_FILENAME=""
 PRE_COMMAND=""
 POST_COMMAND=""
 
@@ -19,7 +23,7 @@ function parseRemote {
   DEVICE=${arr[1]}
 
   if [[ -z "$DEVICE" ]]; then
-    printf "[$ME] Programmer port not specified\\n"
+    printf "[$ME] Programmer port not specified!\\n"
   else
     # Put the device into the params for the remote.
     PARAMS="$PARAMS -P $DEVICE"
@@ -40,6 +44,7 @@ function parseRetryCommand {
 
 function parseProgrammer {
   if [[ $1 == "arduino" ]]; then
+    # Currently arduino is a special case and runs RESET_BAUD
     RESET_BAUD=1
   fi
   PARAMS="$PARAMS -c $1"
@@ -57,18 +62,21 @@ function parseMemoryOperation {
     w) MEM_OP_TYPE=3 ;;
   esac
 
-  # Path to local file
   FILE_PATH=${arr[2]}
+  FILENAME="${FILE_PATH##*/}"
 
+  # Save path to local file and use a session specific filename on remote
   if [[ ${arr[0]} == "flash" ]]; then
-    # Use a session specific filename on remote
-    BASE_FILENAME="${FILE_PATH##*/}_$SESSION"
-  else
-    # This is not really needed, since fuses are always probably specified on the command line?
-    BASE_FILENAME="${FILE_PATH##*/}"
+    FLASH_PATH=$FILE_PATH
+    FLASH_FILENAME=$FILENAME"_"$SESSION
+    FILENAME=$FLASH_FILENAME
+  elif [[ ${arr[0]} == "eeprom" ]]; then
+    EEPROM_PATH=$FILE_PATH
+    EEPROM_FILENAME=$FILENAME"_"$SESSION
+    FILENAME=$EEPROM_FILENAME
   fi
 
-  arr[2]=$BASE_FILENAME
+  arr[2]=$FILENAME
 
   # Rejoin array and add to params
   SAVE_IFS=$IFS
@@ -80,22 +88,14 @@ function parseMemoryOperation {
 
 function connect {
   printf "[$ME] Connecting to remote host...\\n"
-  if ssh -NfM -o $CONTROL_PATH $HOST; then
-    printf "[$ME] Connected\\n"
-  else
+  if ! ssh -NfM -o $CONTROL_PATH $HOST; then
     return 1
   fi
 }
 
 function disconnect {
-  printf "[$ME] Disconnecting from remote host..."
+  printf "[$ME] Disconnecting from remote host...\\n"
   ssh -o $CONTROL_PATH -O exit $HOST
-  printf "\\n"
-}
-
-function copyToRemote {
-  printf "[$ME] Copying file to remote host...\\n"
-  scp -o $CONTROL_PATH $FILE_PATH $HOST:~/$BASE_FILENAME
 }
 
 function pre_command {
@@ -130,15 +130,41 @@ function resetBaud {
   sleep 1
 }
 
+function copyToRemote {
+  if [[ -n "$FLASH_PATH" ]]; then
+    printf "[$ME] Copying flash file to remote host...\\n"
+    if ! scp -o $CONTROL_PATH $FLASH_PATH $HOST:~/$FLASH_FILENAME; then
+      return 1
+    fi
+  fi
+  if [[ -n "$EEPROM_PATH" ]]; then
+    printf "[$ME] Copying eeprom file to remote host...\\n"
+    scp -o $CONTROL_PATH $EEPROM_PATH $HOST:~/$EEPROM_FILENAME
+  fi
+}
+
 function copyFromRemote {
-  printf "[$ME] Copying file from remote host...\\n"
-  scp -o $CONTROL_PATH $HOST:~/$BASE_FILENAME $FILE_PATH
+  if [[ -n "$FLASH_PATH" ]]; then
+    printf "[$ME] Copying flash file from remote host...\\n"
+    if ! scp -o $CONTROL_PATH $HOST:~/$FLASH_FILENAME $FLASH_PATH; then
+      return 1
+    fi
+  fi
+  if [[ -n "$EEPROM_PATH" ]]; then
+    printf "[$ME] Copying eeprom from remote host...\\n"
+    scp -o $CONTROL_PATH $HOST:~/$EEPROM_FILENAME $EEPROM_PATH
+  fi
 }
 
 function delete {
-  printf "[$ME] Deleting file from remote host..."
-  ssh -o $CONTROL_PATH $HOST "rm ~/$BASE_FILENAME"
-  printf "Done\\n"
+  if [[ -n "$FLASH_PATH" ]]; then
+    printf "[$ME] Deleting flash file from remote host...\\n"
+    ssh -o $CONTROL_PATH $HOST "rm ~/$FLASH_FILENAME"
+  fi
+  if [[ -n "$EEPROM_PATH" ]]; then
+    printf "[$ME] Deleting eeprom file from remote host...\\n"
+    ssh -o $CONTROL_PATH $HOST "rm ~/$EEPROM_FILENAME"
+  fi
 }
 
 
@@ -226,7 +252,7 @@ if connect; then
   # No memory operations, just run avrdude with the provided options
   if [[ $MEM_OP_TYPE -eq 0 ]]; then
     if pre_command; then
-      printf "[$ME] Executing avrdude..."
+      printf "[$ME] Executing avrdude...\\n"
       if execute; then
         post_command
       fi
@@ -236,15 +262,15 @@ if connect; then
   # Read requested from board
   if [[ $MEM_OP_TYPE -eq 1 ]]; then
     if pre_command; then
-      printf "[$ME] Reading from board..."
+      printf "[$ME] Reading from board...\\n"
       if execute; then
         if post_command; then
           if copyFromRemote; then
             result=0
           fi
         fi
-        delete
       fi
+      delete
     fi
   fi
 
@@ -252,7 +278,7 @@ if connect; then
   if [[ $MEM_OP_TYPE -eq 2 ]]; then
     if copyToRemote; then
       if pre_command; then
-        printf "[$ME] Verifying..."
+        printf "[$ME] Verifying...\\n"
         if execute; then
           printf "[$ME] Verification succeeded!"
           post_command
@@ -261,8 +287,8 @@ if connect; then
           printf "[$ME] Verification failed!"
         fi
       fi
-      delete
     fi
+    delete
   fi
 
   # Upload to board requested
@@ -271,15 +297,15 @@ if connect; then
       if pre_command; then
         printf "[$ME] Uploading to board...\\n"
         if execute; then
-          printf "[$ME] Upload succeeded!"
+          printf "[$ME] Upload succeeded!\\n"
           post_command
           result=0
         else
-          printf "[$ME] Upload failed!"
+          printf "[$ME] Upload failed!\\n"
         fi
       fi
-      delete
     fi
+    delete
   fi
 
   disconnect
